export const SET_GLOBAL_ERROR = 'error/SET_GLOBAL_ERROR';

export const SET_SIGNIN_ERROR = 'error/SET_SIGNIN_ERROR';
export const SET_SIGNUP_ERRORS = 'error/SET_SIGNUP_ERRORS';

export const SET_SOCIAL_LOGIN_ERROR = 'error/SET_SOCIAL_LOGIN_ERROR';

export const SET_PASSWORD_CHANGE_ERROR = 'error/SET_PASSWORD_CHANGE_ERROR';
export const SET_FORGOT_PASSWORD_ERROR = 'error/SET_FORGOT_PASSWORD_ERROR';
export const SET_RESET_PASSWORD_ERROR = 'error/SET_RESET_PASSWORD_ERROR';
