export const GLOBAL_ERROR_SET = 'GLOBAL_ERROR_SET';

export const SIGNIN_ERROR_SET = 'SIGNIN_ERROR_SET';
export const SIGNUP_ERRORS_SET = 'SIGNUP_ERRORS_SET';

export const SOCIAL_LOGIN_ERROR_SET = 'SOCIAL_LOGIN_ERROR_SET';

export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
export const FORGOT_PASSWORD_ERROR_SET = 'FORGOT_PASSWORD_ERROR_SET';
export const RESET_PASSWORD_ERROR_SET = 'RESET_PASSWORD_ERROR_SET';
