export const USER_LOGIN = 'USER_LOGIN';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_GOOGLE_LOGIN = 'USER_GOOGLE_LOGIN';

export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_GET = 'USER_GET';
export const USER_SET = 'USER_SET';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SET = 'USER_UPDATE_SET';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
