export const USER_LOGIN = 'USER_LOGIN';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_GOOGLE_LOGIN = 'USER_GOOGLE_LOGIN';

export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_GET = 'USER_GET';
export const USER_SET = 'USER_SET';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SET = 'USER_UPDATE_SET';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

export const SET_LOADER = 'SET_LOADER';

export const GLOBAL_ERROR_SET = 'GLOBAL_ERROR_SET';

export const SIGNIN_ERROR_SET = 'SIGNIN_ERROR_SET';
export const SIGNUP_ERRORS_SET = 'SIGNUP_ERRORS_SET';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const FORGOT_PASSWORD_ERROR_SET = 'FORGOT_PASSWORD_ERROR_SET';
export const RESET_PASSWORD_ERROR_SET = 'RESET_PASSWORD_ERROR_SET';

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';

export const SOCIAL_LOGIN_ERROR_SET = 'SOCIAL_LOGIN_ERROR_SET';
